# Site
name: "rfazriansyahyuli"
title: "rfazriansyahyuli"
description: "Cultivate a Greener Tomorrow"
logo: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiz9LgkiEQyycWEDQWcVLqpO9tbpeTUgV6_cl-F5WunyvOivnEC5I59-xi_nxqzN_q1yLHt85AKCcww_Op_wdID8cWDhobOaBlut4qep18gCYm0WeguqWPtbnUsZw9DCYeAg7Cc0oaSB7sW8DxUzslhDOMjWE4s4NuukAvr6NSWST9r6f5XkcZGiYUGIpU/s1600/20240830_143612.png'
favicon: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiz9LgkiEQyycWEDQWcVLqpO9tbpeTUgV6_cl-F5WunyvOivnEC5I59-xi_nxqzN_q1yLHt85AKCcww_Op_wdID8cWDhobOaBlut4qep18gCYm0WeguqWPtbnUsZw9DCYeAg7Cc0oaSB7sW8DxUzslhDOMjWE4s4NuukAvr6NSWST9r6f5XkcZGiYUGIpU/s1600/20240830_143612.png'
baseurl: /
google_analytics: 'UA-246564983-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  admin:
    name: Admin
    display_name: Admin
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: /aboutme
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 8
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

